{% set name = "jieba" %}
{% set version = "0.42.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 055ca12f62674fafed09427f176506079bc135638a14e23e25be909131928db2

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python

  run:
    - python

test:
  imports:
    - jieba

about:
  home: https://github.com/fxsjy/jieba
  # No license in MANIFEST - See https://github.com/fxsjy/jieba/pull/457
  license_file: {{ RECIPE_DIR }}/LICENSE
  license: MIT
  license_family: MIT
  summary: Chinese Words Segementation Utilities
  dev_url: https://github.com/fxsjy/jieba
  doc_url: https://github.com/fxsjy/jieba

extra:
  recipe-maintainers:
    - pmlandwehr
